blueprint:
  name: Fan Control (Off / 1 / 2 / 3)
  description: >
    Uses four buttons on a MOES/Tuya Zigbee remote (TS004F) to send
    the correct IR code—fan OFF, speed 1, 2 or 3—via an IR blaster
    that exposes a text entity.
  domain: automation
  source_url: https://gist.github.com/your-gist-url   # optional
  input:
    remote_device:
      name: Remote (MOES TS004F)
      description: Select the Zigbee/MQTT remote whose buttons fire the triggers.
      selector:
        device:
          integration: mqtt
    text_entity:
      name: IR command text entity
      description: The *text* entity that your IR blaster monitors and sends.
      selector:
        entity:
          domain: text
    fan_off_code:
      name: IR code – Fan OFF
      description: Base-64 string that turns the fan off.
      selector:
        text:
      default: "A/MEpwFAAwPcAfME4AcDBfMEpwGnAUAFwAMBJSDACQGnAcAJ4AEHEfMEpwGnAfMEpwHzBKcB8wTcAQ=="
    fan_1_code:
      name: IR code – Fan 1
      description: Base-64 string for speed 1.
      selector:
        text:
      default: "A/cElAFAAwPCAfcE4BMDAJQgHwX3BMsc9wRACQGUAcArAZQB4AEDwBPABwH3BOAJL8AbwAdAP8ALAfcE4AUv4AMbQCNAD+ACAwIE9wQ="
    fan_2_code:
      name: IR code – Fan 2
      description: Base-64 string for speed 2.
      selector:
        text:
      default: "A/QElQFAAwPCAfQEwAMAleACC0ATA/QElQFABwfCAR0g9ASVAUADA8IB9ATgDwMB9ASAHwGVAeARLwGVAeABAwP0BJUBQEsBlQFAL4AJQAXgCwMNlQH0BPQEwgGVAfQElQE="
    fan_3_code:
      name: IR code – Fan 3
      description: Base-64 string for speed 3.
      selector:
        text:
      default: "A/cElAFAAwPBAfcEwAMB9wTgBQ9AFwL3BJQgIQPRHPcEQAcBlAFAE8ADAfcE4AUPBZQB9wT3BEAF4AUvQBFAMwP3BJQBQAfgAwMF9wSUAfcE4AUvwB8D9wSUAcALwAcF9wSUAfcE"

mode: single

variables:
  ir_codes:
    fan_off: !input fan_off_code
    fan_1:  !input fan_1_code
    fan_2:  !input fan_2_code
    fan_3:  !input fan_3_code

trigger:
  # Fan OFF (button 1)
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: 1_single
    id: fan_off

  # Fan 1 (button 2)
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: 2_single
    id: fan_1

  # Fan 2 (button 3)
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: 3_single
    id: fan_2

  # Fan 3 (button 4)
  - platform: device
    device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: 4_single
    id: fan_3

action:
  - service: text.set_value
    target:
      entity_id: !input text_entity
    data:
      value: "{{ ir_codes[trigger.id] }}"
