blueprint:
  name: Motion light with auto-off
  description: Turn a light on when motion is detected, then turn it off after X s of no motion
  domain: automation

  input:
    motion_sensor:
      name: Motion (or occupancy) sensor
      selector:
        entity:
          domain: binary_sensor
          device_class:            # ← these two keys are **allowed** here
            - motion
            - occupancy

    light_switch:
      name: Light or switch
      selector:
        entity:
          domain:                  # multiple domains are OK here too
            - light
            - switch

    no_motion_duration:
      name: No-motion delay (s)
      default: 60        # change this default if you like
      selector:
        number:
          min: 1         # keep if you still want a lower bound; remove if not needed
          unit_of_measurement: seconds
          mode: box


trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: motion_detected

  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for:
      seconds: !input no_motion_duration
    id: no_motion

action:
  - choose:
      - conditions: "{{ trigger.id == 'motion_detected' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input light_switch    # entity-ID target

      - conditions: "{{ trigger.id == 'no_motion' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input light_switch    # entity-ID target

mode: restart
