blueprint:
  name: Motion Light with Auto-Off Timer
  description: Turn on a light when motion is detected and automatically turn it off after no motion is detected
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy

    light_switch:
      name: Light / Switch
      selector:
        entity:
          domain:
            - light
            - switch

    no_motion_duration:
      name: No-motion delay (s)
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds
          mode: slider
      default: 60

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: motion_detected

  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for:
      seconds: !input no_motion_duration
    id: no_motion

condition: []

action:
  - choose:
      - conditions: "{{ trigger.id == 'motion_detected' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input light_switch

      - conditions: "{{ trigger.id == 'no_motion' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input light_switch

mode: restart
